### ISSUE TITLE
Iframes are not correctly sized on mobile

### ISSUE THREAD

**Issue by kshep92** [raivis-vitols/ghost-theme-willow#8]
Iframes (particualrly YouTube embeds) bleed off the edges of the screen on mobile (portrait) and there is no scrolling available to bring the rest of the play controls back into view. I think an additional style rule is needed somewhere.

**Comment by raivis-vitols** [comment]
@kshep92 Hi! Thanks for opening an issue. Will try to check this and see what can be done once have a free moment. I'm not YouTube video expert, but I think they come with static width and height - this is probably what causes the issue. Style rule won't help then. Well, will see.

**Comment by spacerockzero** [comment]
I use this theme, and also embed youtube vids. I've used this css-only method for automatically resizing iframes and youtube embeds in content:

In your content, wrap the embed in `<div class="flex-video">`, then:

``` css
.flex-video {
  height:0;
  overflow:hidden;
  padding-bottom:67.5%;
  position:relative;
  margin-bottom:2em
}
.flex-video embed, 
.flex-video iframe, 
.flex-video object, 
.flex-video video {
  height:100%;
  max-height:630px;
  position:absolute;
  top:0;
  width:100%;
  max-width:1120px;
  left:0
}
```

I also added the max-height and width to keep the vid embed from getting ginormous on large screens like 4k or apple thunderbolt.
It's the cleanest non-js way I've seen, and has decent resize framerate as well.

See it on this theme in action here: http://www.developervids.com/playlist-nodevember-2015/

Here is a vanillaJS solution that doesn't require a wrapper: https://toddmotto.com/fluid-and-responsive-youtube-and-vimeo-videos-with-fluidvids-js/

I chose the CSS with wrapper solution because I write content using macros, and it ended up being less client-side code downloaded to the browser.
